import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const roboto = localFont({
  src: [
    {
      path: "../fonts/roboto/Roboto-Thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../fonts/roboto/Roboto-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/roboto/Roboto-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/roboto/Roboto-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-roboto",
});

const raleway = localFont({
  src: "../fonts/Raleway-Black.ttf",
  variable: "--font-raleway",
});

const nakamori = localFont({
  src: "../fonts/Nakamori.ttf",
  variable: "--font-nakamori",
});

const cinecaption = localFont({
  src: "../fonts/cinecaption.ttf",
  variable: "--font-cinecaption",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} ${raleway.variable} ${nakamori.variable} ${cinecaption.variable} font-roboto`}
    >
      <body className="dark">{children}</body>
    </html>
  );
}
